server:
  port: 8092
  servlet:
    context-path: /property-view

spring:
  application:
    name: hotel-backend
  profiles:
    active: h2

  jpa:
    hibernate:
      ddl-auto: validate

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true



